{% set name = "isotomics-automated" %}
{% set version = "0.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/csernica/isotomics/archive/refs/tags/v0.1.0.tar.gz
  sha256: bbe59a271a4fc7d95478da4b106b36cb8c49119f73a00c56345efb9e22318a0f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.10.12
    - pip
    - numpy >=1.23.5
    - setuptools
    - wheel
  run:
    - python >=3.10.12
    - numpy >=1.23.5
    - pandas >=2.0.0
    - tqdm
    - matplotlib >=3.10.0
    - seaborn >=0.13.0
    - networkx >=3.1
    - sympy >=1.12
    - scipy >=1.14.0

test:
  imports:
    - isotomics
  commands:
    - python -c "import isotomics"

about:
  home: https://github.com/csernica/isotomics
  dev_url: https://github.com/csernica/isotomics
  summary: "M+1 data processing and simulation for Orbitrap-IRMS fragmentation experiments"
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - csernica
